### ISSUE TITLE
A process in the process pool was terminated abruptly while the future was running or pending

### ISSUE THREAD

**Issue by clb92** [karansthr/Playlist-Length#4]
I finally got it running with python3.5 (tried for some time with python 2.7 but gave up).

I had to install ```python-magic``` and ```futures``` manually, but now I can run ```playlistlen --help``` without any import errors.

I'm getting this error now though:
```
$ playlistlen /volume1/video/Movies/

Filtering videos:   0%|                                                                                                                                                                                                | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/bin/playlistlen", line 11, in <module>
    sys.exit(main())
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/playlist_length/main.py", line 159, in main
    result = video_len_calculator(args.path, args.no_subdir)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/playlist_length/main.py", line 100, in video_len_calculator
    path = task.result()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by clb92** [comment]
It seems to still be a 'magic' error I'm having. Manually running ```print(magic.from_file("video file path here", mime=True))``` prints ```Aborted```

**Comment by clb92** [comment]
It was python-magic (0.4.15) via pip.

I just tried with the package "filemagic" (1.6) instead, and it also imports correctly, but when I run a small test of ```magic.from_file()``` I now get:

```
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/bin/playlistlen", line 7, in <module>
    from playlist_length.main import main
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/playlist_length/main.py", line 9, in <module>
    import magic
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/magic/__init__.py", line 18, in <module>
    from magic.identify import Magic, MagicError
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/magic/identify.py", line 16, in <module>
    from magic import api
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/magic/api.py", line 22, in <module>
    raise ImportError('Unable to find magic library')
ImportError: Unable to find magic library
```

I thought it might be a problem with the libmagic library on this Synology server, so I just installed libmagic 5.25-2, but it hasn't changed anything.

**Comment by mohi7solanki** [comment]
Can you try installing python-magic with python3.5 -m pip install --user python-magic? and try again.. and yeah first uninstall python-magic

**Comment by clb92** [comment]
Did ```python3 -m pip install --user python-magic``` as my regular user, but still no luck.

```print(magic.from_file("test.mp4", mime=True))``` still simply prints "Aborted"

And running unmodified version of ```playlistlen``` now still gives me the same "concurrent.futures.process.BrokenProcessPool" exception.

**Comment by mohi7solanki** [comment]
Weird, `print(magic.from_file("test.mp4", mime=True))` is this line raising some exception or simply printing Aborted?

**Comment by clb92** [comment]
It simply prints "Aborted".

**Comment by mohi7solanki** [comment]
I am closing this issue, for now you can raise an issue on python-magic repo because it seems your magic is not properly installed.

**Comment by mohi7solanki** [comment]
try installing libmagic  manually.
